// AUTOGENERATED FILE FROM png2asset
//  Conversion args: c_10_trefle.png -c /c_10_trefle.c -map -noflip

#ifndef METASPRITE_c_10_trefle_H
#define METASPRITE_c_10_trefle_H

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

#define c_10_trefle_TILE_ORIGIN 0
#define c_10_trefle_TILE_W 8
#define c_10_trefle_TILE_H 8
#define c_10_trefle_WIDTH 16
#define c_10_trefle_HEIGHT 16
#define c_10_trefle_TILE_COUNT 4
#define c_10_trefle_PALETTE_COUNT 1
#define c_10_trefle_COLORS_PER_PALETTE 4
#define c_10_trefle_TOTAL_COLORS 4
#define c_10_trefle_MAP_ATTRIBUTES 0
extern const unsigned char c_10_trefle_map[4];
#define c_10_trefle_map_attributes c_10_trefle_map

BANKREF_EXTERN(c_10_trefle)

extern const palette_color_t c_10_trefle_palettes[4];
extern const uint8_t c_10_trefle_tiles[64];

#endif
