// AUTOGENERATED FILE FROM png2asset
//  Conversion args: c_5_carreau.png -c /c_5_carreau.c -map -noflip

#ifndef METASPRITE_c_5_carreau_H
#define METASPRITE_c_5_carreau_H

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

#define c_5_carreau_TILE_ORIGIN 0
#define c_5_carreau_TILE_W 8
#define c_5_carreau_TILE_H 8
#define c_5_carreau_WIDTH 16
#define c_5_carreau_HEIGHT 16
#define c_5_carreau_TILE_COUNT 4
#define c_5_carreau_PALETTE_COUNT 1
#define c_5_carreau_COLORS_PER_PALETTE 4
#define c_5_carreau_TOTAL_COLORS 4
#define c_5_carreau_MAP_ATTRIBUTES 0
extern const unsigned char c_5_carreau_map[4];
#define c_5_carreau_map_attributes c_5_carreau_map

BANKREF_EXTERN(c_5_carreau)

extern const palette_color_t c_5_carreau_palettes[4];
extern const uint8_t c_5_carreau_tiles[64];

#endif
