// AUTOGENERATED FILE FROM png2asset
//  Conversion args: c_9_pique.png -c /c_9_pique.c -map -noflip

#ifndef METASPRITE_c_9_pique_H
#define METASPRITE_c_9_pique_H

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

#define c_9_pique_TILE_ORIGIN 0
#define c_9_pique_TILE_W 8
#define c_9_pique_TILE_H 8
#define c_9_pique_WIDTH 16
#define c_9_pique_HEIGHT 16
#define c_9_pique_TILE_COUNT 4
#define c_9_pique_PALETTE_COUNT 1
#define c_9_pique_COLORS_PER_PALETTE 4
#define c_9_pique_TOTAL_COLORS 4
#define c_9_pique_MAP_ATTRIBUTES 0
extern const unsigned char c_9_pique_map[4];
#define c_9_pique_map_attributes c_9_pique_map

BANKREF_EXTERN(c_9_pique)

extern const palette_color_t c_9_pique_palettes[4];
extern const uint8_t c_9_pique_tiles[64];

#endif
