//AUTOGENERATED FILE FROM png2asset
// Conversion args: c_A_coeur.png -c /c_A_coeur.c -map -noflip

#ifndef METASPRITE_c_A_coeur_H
#define METASPRITE_c_A_coeur_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define c_A_coeur_TILE_ORIGIN 0
#define c_A_coeur_TILE_W 8
#define c_A_coeur_TILE_H 8
#define c_A_coeur_WIDTH 16
#define c_A_coeur_HEIGHT 16
#define c_A_coeur_TILE_COUNT 4
#define c_A_coeur_PALETTE_COUNT 1
#define c_A_coeur_COLORS_PER_PALETTE 4
#define c_A_coeur_TOTAL_COLORS 4
#define c_A_coeur_MAP_ATTRIBUTES 0
extern const unsigned char c_A_coeur_map[4];
#define c_A_coeur_map_attributes c_A_coeur_map

BANKREF_EXTERN(c_A_coeur)

extern const palette_color_t c_A_coeur_palettes[4];
extern const uint8_t c_A_coeur_tiles[64];

#endif
