//AUTOGENERATED FILE FROM png2asset
// Conversion args: c_Q_pique.png -c /c_Q_pique.c -map -noflip

#ifndef METASPRITE_c_Q_pique_H
#define METASPRITE_c_Q_pique_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define c_Q_pique_TILE_ORIGIN 0
#define c_Q_pique_TILE_W 8
#define c_Q_pique_TILE_H 8
#define c_Q_pique_WIDTH 16
#define c_Q_pique_HEIGHT 16
#define c_Q_pique_TILE_COUNT 4
#define c_Q_pique_PALETTE_COUNT 1
#define c_Q_pique_COLORS_PER_PALETTE 4
#define c_Q_pique_TOTAL_COLORS 4
#define c_Q_pique_MAP_ATTRIBUTES 0
extern const unsigned char c_Q_pique_map[4];
#define c_Q_pique_map_attributes c_Q_pique_map

BANKREF_EXTERN(c_Q_pique)

extern const palette_color_t c_Q_pique_palettes[4];
extern const uint8_t c_Q_pique_tiles[64];

#endif
