//AUTOGENERATED FILE FROM png2asset
// Conversion args: CasinoCroupier1.png -c asset_croupier1.c -map -noflip

#ifndef METASPRITE_asset_croupier1_H
#define METASPRITE_asset_croupier1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define asset_croupier1_TILE_ORIGIN 0
#define asset_croupier1_TILE_W 8
#define asset_croupier1_TILE_H 8
#define asset_croupier1_WIDTH 32
#define asset_croupier1_HEIGHT 40
#define asset_croupier1_TILE_COUNT 17
#define asset_croupier1_PALETTE_COUNT 1
#define asset_croupier1_COLORS_PER_PALETTE 4
#define asset_croupier1_TOTAL_COLORS 4
#define asset_croupier1_MAP_ATTRIBUTES 0
extern const unsigned char asset_croupier1_map[20];
#define asset_croupier1_map_attributes asset_croupier1_map

BANKREF_EXTERN(asset_croupier1)

extern const palette_color_t asset_croupier1_palettes[4];
extern const uint8_t asset_croupier1_tiles[272];

#endif
