//AUTOGENERATED FILE FROM png2asset
// Conversion args: border.png -c border.c -map -noflip

#ifndef METASPRITE_border_H
#define METASPRITE_border_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define border_TILE_ORIGIN 0
#define border_TILE_W 8
#define border_TILE_H 8
#define border_WIDTH 8
#define border_HEIGHT 8
#define border_TILE_COUNT 1
#define border_PALETTE_COUNT 1
#define border_COLORS_PER_PALETTE 4
#define border_TOTAL_COLORS 4
#define border_MAP_ATTRIBUTES 0
extern const unsigned char border_map[1];
#define border_map_attributes border_map

BANKREF_EXTERN(border)

extern const palette_color_t border_palettes[4];
extern const uint8_t border_tiles[16];

#endif
