// AUTOGENERATED FILE FROM png2asset
//  Conversion args: border.png -c border.c -map -noflip

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

BANKREF(border)

const palette_color_t border_palettes[4] = {RGB8(0, 0, 0), RGB8(0, 0, 0),
                                            RGB8(0, 0, 0), RGB8(0, 0, 0)};

const uint8_t border_tiles[16] = {0xff, 0x00, 0x00, 0x00, 0x00, 0x00,
                                  0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                                  0x00, 0x00, 0x00, 0x00};

const unsigned char border_map[1] = {
    0x00,
};
