//AUTOGENERATED FILE FROM png2asset
// Conversion args: button.png -c button.c -map -noflip

#ifndef METASPRITE_button_H
#define METASPRITE_button_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define button_TILE_ORIGIN 0
#define button_TILE_W 8
#define button_TILE_H 8
#define button_WIDTH 8
#define button_HEIGHT 8
#define button_TILE_COUNT 1
#define button_PALETTE_COUNT 1
#define button_COLORS_PER_PALETTE 4
#define button_TOTAL_COLORS 4
#define button_MAP_ATTRIBUTES 0
extern const unsigned char button_map[1];
#define button_map_attributes button_map

BANKREF_EXTERN(button)

extern const palette_color_t button_palettes[4];
extern const uint8_t button_tiles[16];

#endif
