// AUTOGENERATED FILE FROM png2asset
//  Conversion args: button.png -c button.c -map -noflip

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

BANKREF(button)

const palette_color_t button_palettes[4] = {RGB8(0, 0, 0), RGB8(0, 0, 0),
                                            RGB8(0, 0, 0), RGB8(0, 0, 0)};

const uint8_t button_tiles[16] = {0x00, 0x00, 0x00, 0x00, 0x18, 0x00,
                                  0x24, 0x00, 0x24, 0x00, 0x18, 0x00,
                                  0x00, 0x00, 0x00, 0x00};

const unsigned char button_map[1] = {
    0x00,
};
