// AUTOGENERATED FILE FROM png2asset
//  Conversion args: LeftRightEyeCroupier.png -c LeftRightEye.c -map -noflip

#ifndef METASPRITE_LeftRightEye_H
#define METASPRITE_LeftRightEye_H

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

#define LeftRightEye_TILE_ORIGIN 0
#define LeftRightEye_TILE_W 8
#define LeftRightEye_TILE_H 8
#define LeftRightEye_WIDTH 8
#define LeftRightEye_HEIGHT 8
#define LeftRightEye_TILE_COUNT 1
#define LeftRightEye_PALETTE_COUNT 1
#define LeftRightEye_COLORS_PER_PALETTE 4
#define LeftRightEye_TOTAL_COLORS 4
#define LeftRightEye_MAP_ATTRIBUTES 0
extern const unsigned char LeftRightEye_map[1];
#define LeftRightEye_map_attributes LeftRightEye_map

BANKREF_EXTERN(LeftRightEye)

extern const palette_color_t LeftRightEye_palettes[4];
extern const uint8_t LeftRightEye_tiles[16];

#endif
