//AUTOGENERATED FILE FROM png2asset
// Conversion args: LeftLeftEyeCroupier.png -c LeftLeftEye.c -map -noflip

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(LeftLeftEye)

const palette_color_t LeftLeftEye_palettes[4] = {
	RGB8(224,248,207), RGB8(  7, 24, 33), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	};

const uint8_t LeftLeftEye_tiles[16] = {
	0xff,0x00,0xff,0x00,0xf8,0x00,0xf0,0x00,0xe0,0x00,0xe6,0x00,0xe8,0x00,0xe4,0x00
	};


const unsigned char LeftLeftEye_map[1] = {
	0x00,
};
