//AUTOGENERATED FILE FROM png2asset
// Conversion args: LeftRightEyeCroupier.png -c LeftRightEye.c -map -noflip

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(LeftRightEye)

const palette_color_t LeftRightEye_palettes[4] = {
	RGB8(224,248,207), RGB8(  7, 24, 33), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	};

const uint8_t LeftRightEye_tiles[16] = {
	0xff,0x00,0xff,0x00,0x1f,0x00,0x0f,0x00,0x07,0x00,0x67,0x00,0x17,0x00,0x87,0x00
	};


const unsigned char LeftRightEye_map[1] = {
	0x00,
};
