// AUTOGENERATED FILE FROM png2asset
//  Conversion args: LeftLeftEyeCroupier.png -c LeftLeftEye.c -map -noflip

#ifndef METASPRITE_LeftLeftEye_H
#define METASPRITE_LeftLeftEye_H

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

#define LeftLeftEye_TILE_ORIGIN 0
#define LeftLeftEye_TILE_W 8
#define LeftLeftEye_TILE_H 8
#define LeftLeftEye_WIDTH 8
#define LeftLeftEye_HEIGHT 8
#define LeftLeftEye_TILE_COUNT 1
#define LeftLeftEye_PALETTE_COUNT 1
#define LeftLeftEye_COLORS_PER_PALETTE 4
#define LeftLeftEye_TOTAL_COLORS 4
#define LeftLeftEye_MAP_ATTRIBUTES 0
extern const unsigned char LeftLeftEye_map[1];
#define LeftLeftEye_map_attributes LeftLeftEye_map

BANKREF_EXTERN(LeftLeftEye)

extern const palette_color_t LeftLeftEye_palettes[4];
extern const uint8_t LeftLeftEye_tiles[16];

#endif
