//AUTOGENERATED FILE FROM png2asset
// Conversion args: CasinoGb.png -c load_screen.c -map

#ifndef METASPRITE_load_screen_H
#define METASPRITE_load_screen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define load_screen_TILE_ORIGIN 0
#define load_screen_TILE_W 8
#define load_screen_TILE_H 8
#define load_screen_WIDTH 160
#define load_screen_HEIGHT 144
#define load_screen_TILE_COUNT 67
#define load_screen_PALETTE_COUNT 1
#define load_screen_COLORS_PER_PALETTE 4
#define load_screen_TOTAL_COLORS 4
#define load_screen_MAP_ATTRIBUTES 0
extern const unsigned char load_screen_map[360];
#define load_screen_map_attributes load_screen_map

BANKREF_EXTERN(load_screen)

extern const palette_color_t load_screen_palettes[4];
extern const uint8_t load_screen_tiles[1072];

#endif
