//AUTOGENERATED FILE FROM png2asset
// Conversion args: slotBorder.png -c slotBorder.c -map -noflip

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(slotBorder)

const palette_color_t slotBorder_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	};

const uint8_t slotBorder_tiles[16] = {
	0x03,0x00,0x07,0x00,0x0e,0x00,0x1c,0x00,0x38,0x00,0x70,0x00,0xe0,0x00,0xc0,0x00
	};


const unsigned char slotBorder_map[1] = {
	0x00,
};
