//AUTOGENERATED FILE FROM png2asset
// Conversion args: slotBorder.png -c slotBorder.c -map -noflip

#ifndef METASPRITE_slotBorder_H
#define METASPRITE_slotBorder_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define slotBorder_TILE_ORIGIN 0
#define slotBorder_TILE_W 8
#define slotBorder_TILE_H 8
#define slotBorder_WIDTH 8
#define slotBorder_HEIGHT 8
#define slotBorder_TILE_COUNT 1
#define slotBorder_PALETTE_COUNT 1
#define slotBorder_COLORS_PER_PALETTE 4
#define slotBorder_TOTAL_COLORS 4
#define slotBorder_MAP_ATTRIBUTES 0
extern const unsigned char slotBorder_map[1];
#define slotBorder_map_attributes slotBorder_map

BANKREF_EXTERN(slotBorder)

extern const palette_color_t slotBorder_palettes[4];
extern const uint8_t slotBorder_tiles[16];

#endif
