// AUTOGENERATED FILE FROM png2asset
//  Conversion args: /Sonic_gb.png -c sonic.c -spr8x8 -sw 16 -sh 16

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

BANKREF(sonic)

const palette_color_t sonic_palettes[4] = {
    RGB8(160, 160, 160), RGB8(54, 54, 54), RGB8(0, 0, 0), RGB8(0, 0, 0)};

const uint8_t sonic_tiles[16] = {0x00, 0x83, 0x00, 0x01, 0x04, 0x81,
                                 0x01, 0x00, 0x4c, 0x83, 0x22, 0x80,
                                 0x2c, 0xc3, 0x6a, 0x91};

const metasprite_t sonic_metasprite0[] = {METASPR_ITEM(-8, -8, 0, S_PAL(0)),
                                          METASPR_TERM};

const metasprite_t *const sonic_metasprites[1] = {sonic_metasprite0};
