// AUTOGENERATED FILE FROM png2asset
//  Conversion args: /Sonic_gb.png -c sonic.c -spr8x8 -sw 16 -sh 16

#ifndef METASPRITE_sonic_H
#define METASPRITE_sonic_H

#include <gbdk/metasprites.h>
#include <gbdk/platform.h>
#include <stdint.h>

#define sonic_TILE_ORIGIN 0
#define sonic_TILE_W 8
#define sonic_TILE_H 8
#define sonic_WIDTH 16
#define sonic_HEIGHT 16
#define sonic_TILE_COUNT 1
#define sonic_PALETTE_COUNT 1
#define sonic_COLORS_PER_PALETTE 4
#define sonic_TOTAL_COLORS 4
#define sonic_PIVOT_X 8
#define sonic_PIVOT_Y 8
#define sonic_PIVOT_W 16
#define sonic_PIVOT_H 16
extern const metasprite_t *const sonic_metasprites[1];

BANKREF_EXTERN(sonic)

extern const palette_color_t sonic_palettes[4];
extern const uint8_t sonic_tiles[16];

#endif
